#!/usr/bin/env python3
"""Analyze TDC code-density calibration captures.

This wrapper uses the existing TDC packet format and writes a compact manifest
plus lane code-density CSV files. It is intended for dedicated calibration
captures generated by RO_TDC_code_density_cal_sysclk_top.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def decode_packets(data: bytes) -> list[dict[str, int]]:
    packets: list[dict[str, int]] = []
    i = 0
    while i + 8 <= len(data):
        if data[i] != 0xA5:
            i += 1
            continue
        frame = data[i:i + 8]
        packets.append(
            {
                "seq": frame[1] | (frame[2] << 8),
                "coarse_lsb": frame[3] | (frame[4] << 8),
                "bin_a": frame[5],
                "bin_b": frame[6],
                "flags": frame[7],
            }
        )
        i += 8
    return packets


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest().upper()


def entropy(values: list[int]) -> tuple[float, float]:
    if not values:
        return 0.0, 0.0
    total = len(values)
    counts = Counter(values)
    probs = [v / total for v in counts.values()]
    return -sum(p * math.log2(p) for p in probs), -math.log2(max(probs))


def seq_gaps(packets: list[dict[str, int]]) -> int:
    gaps = 0
    for prev, cur in zip(packets, packets[1:]):
        if cur["seq"] != ((prev["seq"] + 1) & 0xFFFF):
            gaps += 1
    return gaps


def code_density(values: list[int], bins: int, clock_period_ps: float) -> list[dict[str, float | int]]:
    counts = Counter(v for v in values if 0 <= v < bins)
    total = sum(counts.values())
    ideal = total / bins if bins else 0.0
    cumulative_width = 0.0
    cumulative_dnl = 0.0
    rows: list[dict[str, float | int]] = []
    for code in range(bins):
        count = counts.get(code, 0)
        probability = count / total if total else 0.0
        width_ps = probability * clock_period_ps
        dnl_lsb = count / ideal - 1.0 if ideal else 0.0
        cumulative_dnl += dnl_lsb
        rows.append(
            {
                "bin": code,
                "count": count,
                "probability": probability,
                "width_ps_nominal": width_ps,
                "ideal_width_ps": clock_period_ps / bins if bins else 0.0,
                "dnl_lsb": dnl_lsb,
                "inl_lsb": cumulative_dnl,
                "phase_center_ps_nominal": cumulative_width + width_ps / 2.0,
                "dead_code": 1 if count == 0 else 0,
            }
        )
        cumulative_width += width_ps
    return rows


def write_csv(path: Path, rows: list[dict[str, float | int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def lane_summary(name: str, values: list[int], rows: list[dict[str, float | int]]) -> dict[str, float | int]:
    h, hmin = entropy(values)
    used = sum(1 for row in rows if int(row["count"]) > 0)
    dnl = [float(row["dnl_lsb"]) for row in rows]
    inl = [float(row["inl_lsb"]) for row in rows]
    return {
        f"{name}_entropy_bin": h,
        f"{name}_min_entropy_bin": hmin,
        f"{name}_used_bins": used,
        f"{name}_dead_bins": len(rows) - used,
        f"{name}_max_dnl_lsb": max(dnl) if dnl else 0.0,
        f"{name}_min_dnl_lsb": min(dnl) if dnl else 0.0,
        f"{name}_peak_abs_inl_lsb": max((abs(v) for v in inl), default=0.0),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--label", required=True)
    parser.add_argument("--out-dir", type=Path, default=ROOT / "data/experiments/tdc_code_density_cal_20260525")
    parser.add_argument("--bins", type=int, default=65)
    parser.add_argument("--clock-period-ps", type=float, default=5000.0)
    parser.add_argument("--bitstream", type=Path)
    parser.add_argument("--board-id", default="z7020_b01")
    args = parser.parse_args()

    data = args.input.read_bytes()
    packets = decode_packets(data)
    if not packets:
        raise SystemExit(f"No A5 TDC packets decoded from {args.input}")

    bin_a = [p["bin_a"] for p in packets]
    bin_b = [p["bin_b"] for p in packets]
    cal_a = code_density(bin_a, args.bins, args.clock_period_ps)
    cal_b = code_density(bin_b, args.bins, args.clock_period_ps)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    lane_a_csv = args.out_dir / f"{args.label}.lane_a_lut.csv"
    lane_b_csv = args.out_dir / f"{args.label}.lane_b_lut.csv"
    manifest_json = args.out_dir / f"{args.label}.manifest.json"
    summary_md = args.out_dir / f"{args.label}.summary.md"
    write_csv(lane_a_csv, cal_a)
    write_csv(lane_b_csv, cal_b)

    summary = {
        "label": args.label,
        "input": str(args.input),
        "capture_sha256": sha256(args.input),
        "capture_bytes": len(data),
        "packets": len(packets),
        "seq_gaps": seq_gaps(packets),
        "bins": args.bins,
        "clock_period_ps": args.clock_period_ps,
        "board_id": args.board_id,
        "bitstream": str(args.bitstream) if args.bitstream else "",
        "bitstream_sha256": sha256(args.bitstream) if args.bitstream and args.bitstream.exists() else "",
        **lane_summary("lane_a", bin_a, cal_a),
        **lane_summary("lane_b", bin_b, cal_b),
        "claim_boundary": "Dedicated calibration smoke; nominal ps mapping assumes near-uniform asynchronous calibration phase coverage.",
    }
    manifest_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    lines = [
        f"# TDC Code-Density Calibration Summary: {args.label}",
        "",
        f"- input: `{args.input}`",
        f"- capture bytes: `{summary['capture_bytes']}`",
        f"- decoded packets: `{summary['packets']}`",
        f"- seq gaps: `{summary['seq_gaps']}`",
        f"- capture SHA256: `{summary['capture_sha256']}`",
        f"- lane A LUT: `{lane_a_csv}`",
        f"- lane B LUT: `{lane_b_csv}`",
        "",
        "## Lane Summary",
        "",
        "| lane | used bins | dead bins | H(bin) | min-H(bin) | max DNL | min DNL | peak abs INL |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        (
            f"| A | {summary['lane_a_used_bins']} | {summary['lane_a_dead_bins']} | "
            f"{summary['lane_a_entropy_bin']:.6f} | {summary['lane_a_min_entropy_bin']:.6f} | "
            f"{summary['lane_a_max_dnl_lsb']:.6f} | {summary['lane_a_min_dnl_lsb']:.6f} | "
            f"{summary['lane_a_peak_abs_inl_lsb']:.6f} |"
        ),
        (
            f"| B | {summary['lane_b_used_bins']} | {summary['lane_b_dead_bins']} | "
            f"{summary['lane_b_entropy_bin']:.6f} | {summary['lane_b_min_entropy_bin']:.6f} | "
            f"{summary['lane_b_max_dnl_lsb']:.6f} | {summary['lane_b_min_dnl_lsb']:.6f} | "
            f"{summary['lane_b_peak_abs_inl_lsb']:.6f} |"
        ),
        "",
        "## Claim Boundary",
        "",
        "This is a dedicated code-density calibration smoke, not yet the full publication calibration set. Use it to check feasibility, dead-code structure, and first-order bin-width LUT generation.",
        "",
    ]
    summary_md.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {lane_a_csv}")
    print(f"Wrote {lane_b_csv}")
    print(f"Wrote {manifest_json}")
    print(f"Wrote {summary_md}")


if __name__ == "__main__":
    main()

